name: airbnb-workflow #name of workflow

on: #the triggers
  workflow_dispatch:
  push:
     branches:
       - main

jobs:
  test: # job identifier...could be anything
    runs-on: ubuntu-latest # set the runner
    steps:
        - name: Get code
          uses: actions/checkout@v3

        - name: Confirm checkout
          run: echo "Code obtained successfully"

        - name: Install .NET
          uses: actions/setup-dotnet@v5
          with:
            dotnet-version: '10.0.x'

        - name: Build project
          run: dotnet build

        - name: Test start
          run: | # we are defining a command to be executed when we use run, pipe symbol for multi line commands
             echo "Tests initialized!!!" 
             echo "Tests have been initialized"

        - name: Test completed
          run: echo "Tests run successfully"

  deploy:
    runs-on: ubuntu-latest
    needs: test # this will make it run after the test job and not in parallel
    steps:
      - name: Get code
        uses: actions/checkout@v3

