name: airbnb-workflow #name of workflow

on: [push, workflow_dispatch] # the triggers

jobs:
  first-job:
    runs-on: ubuntu-latest # set the runner
    steps: 
        - name: Echo greeting
          run: | # we are defining a command to be executed when we use run, pipe symbol for multi line commands
             echo "Hello World!!!" 
             echo "This is a .NET project"

        - name: Echo goodbye
          run: echo "Goodbye"

